server:
    port: 3001
spring:
    application:
        name: Meu App

    devtools:
        restart:
            enabled: false

    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            fail-on-empty-beans: false

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                format_sql: true
                ddl-auto: none
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true

    datasource:
        url: jdbc:postgresql://localhost:5432/lista-telefonica
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver